# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: 3.5
      after_success:
        - Rscript -e 'covr::codecov()'
      before_deploy:
        - Rscript -e 'remotes::install_cran("pkgdown")'
        - Rscript -e 'remotes::install_github("tidyverse/tidytemplate")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - r: devel

env:
  global:
    - MAKEFLAGS="-j 2"
